### ISSUE TITLE
Not an issue! More of a word.

### ISSUE THREAD

**Issue by loneicewolf** [volticks/CTF-Writeups#1]
# Hi!
I just came across this repo while browsing for CTF's, and I have to say this one has a very organized structure. **`:)`**
I just thought of letting you know this, and a thank-you for making this repo as well. This "issue" can be closed. This repo is a great "template" for others who also do CTF's (even if I - at the moment - doesn't really do CTF's).

### Have a great covid-free week!

//Wishes from Sweden!

**Comment by volticks** [comment]
Thx 😳
